Types

***

In [1]:
15 / (5 * 6)


0.5

1256
 x65
----


INT

***

In [2]:
f'{123:08b}'


'01111011'

In [3]:
'123'

'123'

In [4]:
123.0


123.0

In [5]:
8 / 2


4.0

In [6]:
type(8/2)

float

In [7]:
type (8//2)

int

numpy

****

In [8]:
import numpy as np

In [9]:
L = [1, 2, 3, 'ABC', [1, 2, 3]]

In [10]:
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # Three dimentional array (matrix)




In [11]:
L = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Takes list of list and store it in a efficient format - numpy array

In [12]:
L

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print (L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
L.dtype # datatype (int32 - integeter stored in 32bits)

dtype('int32')

In [15]:
L = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype = float)

In [16]:
print (L)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [17]:
np.arange(9).reshape(3, 3) # https://numpy.org/

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.arange(9).reshape(3, 3) + 1 # https://numpy.org/

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.random.randint(1, 7) # https://numpy.org/devdocs/reference/random/index.html
                        

2

In [20]:
np.random.randint(1, 7, 1000)  # roll a die.

array([2, 6, 5, 2, 4, 1, 6, 3, 6, 3, 1, 5, 5, 3, 1, 3, 3, 6, 3, 6, 2, 3,
       4, 6, 3, 5, 4, 5, 4, 6, 2, 4, 6, 3, 6, 3, 5, 5, 6, 5, 5, 4, 2, 3,
       3, 2, 1, 3, 1, 6, 4, 4, 6, 5, 5, 6, 6, 5, 4, 5, 6, 5, 4, 4, 1, 3,
       2, 4, 5, 1, 1, 3, 3, 4, 2, 5, 3, 3, 3, 1, 1, 6, 2, 6, 2, 3, 3, 6,
       5, 6, 3, 3, 5, 1, 5, 4, 3, 3, 1, 4, 5, 1, 1, 1, 6, 6, 5, 3, 3, 1,
       1, 5, 4, 5, 4, 2, 3, 1, 6, 5, 3, 2, 3, 6, 4, 2, 4, 1, 3, 3, 1, 3,
       1, 2, 2, 4, 2, 3, 1, 6, 5, 5, 6, 3, 2, 2, 6, 5, 1, 5, 4, 3, 5, 3,
       2, 4, 2, 1, 5, 2, 6, 4, 5, 3, 4, 6, 4, 5, 5, 4, 1, 1, 1, 5, 1, 4,
       1, 4, 6, 3, 1, 2, 4, 3, 2, 1, 3, 1, 5, 6, 4, 1, 2, 5, 3, 6, 2, 5,
       4, 6, 6, 6, 5, 5, 3, 4, 4, 6, 2, 3, 2, 2, 1, 5, 4, 6, 2, 1, 2, 1,
       3, 2, 3, 2, 6, 1, 5, 3, 5, 3, 4, 1, 5, 4, 3, 2, 4, 2, 5, 5, 6, 1,
       5, 4, 5, 4, 2, 5, 1, 6, 5, 5, 1, 4, 4, 4, 4, 1, 4, 3, 6, 6, 2, 2,
       4, 2, 2, 3, 6, 1, 6, 5, 6, 4, 6, 5, 2, 4, 5, 6, 3, 5, 2, 3, 3, 6,
       4, 1, 6, 1, 5, 2, 5, 4, 5, 5, 4, 1, 1, 4, 3,

In [21]:
rolls = np.random.randint(1, 7, 1000)  # roll a die.

In [22]:

np.mean(rolls) # average roll.

3.529

In [23]:
np.std(rolls)   # spread


1.7021042858767497

In [24]:
likert = np.random.randint(1, 8, 1000)  # likert scale

In [25]:
np.mean(likert)

4.059

In [26]:
np.median(likert) # median


4.0

## Counts
***

In [27]:
rolls[:10] # Peak at the first ten values

array([5, 5, 4, 1, 4, 1, 5, 2, 5, 1])

In [28]:
# Unique values in the array

np.unique(rolls)



array([1, 2, 3, 4, 5, 6])

In [29]:
# Counts. 
np.unique(rolls,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([164, 150, 185, 171, 154, 176], dtype=int64))

In [33]:
# Counts. 
un_rolls, counts = np.unique(rolls,return_counts=True)

un_rolls, counts

(array([1, 2, 3, 4, 5, 6]), array([164, 150, 185, 171, 154, 176], dtype=int64))

In [34]:
# Bar chart.

import matplotlib.pyplot as plt   # https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.bar.html

plt.bar(un_rolls, counts)

<BarContainer object of 6 artists>

In [36]:
np.mean([1,2,2,2,3,4,5,6,7,8,8,8,9,10])

5.357142857142857

In [37]:
np.mean([1,1,1,1,1,1,1,10,10,10,10,10,10,10])

5.5

### END

****