Types

***

In [ ]:
15 / (5 * 6)


1256
 x65
----


INT

***

In [3]:
f'{123:08b}'


'01111011'

In [4]:
'123'

'123'

In [5]:
123.0


123.0

In [1]:
8 / 2


4.0

In [2]:
type(8/2)

float

In [3]:
type (8//2)

int

numpy

****

In [4]:
import numpy as np

In [6]:
L = [1, 2, 3, 'ABC', [1, 2, 3]]

In [ ]:
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # Three dimentional array (matrix)




In [7]:
L = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Takes list of list and store it in a efficient format - numpy array

In [8]:
L

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print (L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
L.dtype # datatype (int32 - integeter stored in 32bits)

dtype('int32')

In [11]:
L = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype = float)

In [12]:
print (L)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [15]:
np.arange(9).reshape(3, 3) # https://numpy.org/

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.arange(9).reshape(3, 3) + 1 # https://numpy.org/

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.random.randint(1, 7) # https://numpy.org/devdocs/reference/random/index.html
                        

4

In [24]:
np.random.randint(1, 7, 1000)  # roll a die.

array([2, 1, 1, 6, 4, 1, 3, 1, 3, 3, 5, 4, 5, 3, 1, 3, 1, 2, 1, 5, 6, 4,
       3, 3, 5, 5, 4, 3, 4, 3, 6, 5, 1, 1, 6, 2, 6, 3, 2, 6, 5, 1, 2, 1,
       6, 1, 3, 4, 1, 3, 6, 6, 6, 3, 5, 3, 4, 6, 6, 3, 1, 2, 1, 6, 2, 4,
       4, 5, 1, 3, 4, 4, 1, 5, 3, 3, 2, 5, 6, 4, 3, 4, 4, 6, 1, 5, 4, 1,
       6, 5, 3, 4, 4, 1, 3, 1, 3, 6, 1, 6, 3, 3, 1, 3, 1, 1, 1, 5, 2, 4,
       2, 5, 6, 4, 4, 5, 6, 4, 3, 1, 5, 5, 6, 5, 5, 6, 4, 6, 1, 1, 4, 2,
       1, 2, 6, 4, 5, 2, 4, 4, 5, 5, 4, 2, 1, 3, 3, 3, 5, 2, 3, 1, 1, 3,
       5, 5, 6, 3, 6, 4, 4, 4, 5, 2, 5, 6, 4, 1, 4, 4, 4, 5, 3, 1, 3, 6,
       3, 1, 4, 2, 4, 1, 2, 4, 5, 5, 6, 5, 3, 6, 5, 1, 4, 6, 3, 2, 6, 2,
       4, 4, 1, 2, 5, 5, 2, 2, 5, 4, 4, 5, 2, 5, 5, 1, 5, 3, 6, 5, 2, 5,
       5, 2, 3, 2, 4, 1, 5, 5, 6, 1, 3, 3, 1, 1, 1, 2, 4, 2, 6, 3, 6, 1,
       1, 1, 5, 5, 1, 1, 3, 3, 2, 3, 4, 4, 2, 4, 5, 1, 1, 2, 4, 1, 1, 5,
       4, 3, 2, 6, 5, 4, 1, 2, 2, 3, 6, 4, 1, 3, 5, 2, 6, 6, 5, 3, 4, 2,
       6, 2, 1, 6, 4, 3, 5, 5, 2, 5, 5, 6, 4, 4, 4,

In [25]:
rolls = np.random.randint(1, 7, 1000)  # roll a die.

In [26]:

np.mean(rolls) # average roll.

3.521